services:
  gateway:
    build: .
    environment:
      GATEWAY_BIND: 0.0.0.0:8080
      GATEWAY_WEBSOCKET_BIND: 0.0.0.0:9000
    expose:
      - "9000"
    ports:
      - "8080:8080"

  home:
    build: .
    command: ["/usr/local/bin/home"]
    depends_on:
      - gateway
    environment:
      HOME_WEBSOCKET_URL: ws://gateway:9000
